#!/bin/bash

#Remove any existing file
mkdir /tmp/dvb

#Grab master files
wget https://raw.githubusercontent.com/CHBMB/Unraid-DVB/master/build_scripts/build.sh -P /tmp/dvb/
wget https://raw.githubusercontent.com/CHBMB/Unraid-DVB/master/build_scripts/kernel-compile-module.sh -P /tmp/dvb/
wget https://raw.githubusercontent.com/CHBMB/Unraid-DVB/master/build_scripts/dd-module.sh -P /tmp/dvb/
wget https://raw.githubusercontent.com/CHBMB/Unraid-DVB/master/build_scripts/libreelec-module.sh -P /tmp/dvb/
wget https://raw.githubusercontent.com/CHBMB/Unraid-DVB/master/build_scripts/tbs-crazy-dvbst-module.sh -P /tmp/dvb/
wget https://raw.githubusercontent.com/CHBMB/Unraid-DVB/master/build_scripts/tbs-os-module.sh -P /tmp/dvb/

#Change permissions
chmod +x /mnt/disk1/dvb/*.sh


